config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :users do
  	member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'home/about' => 'home#about'
  get 'search' => 'searchs#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	
		def self.search(search, word)
		if search == "forward_match"
			@book = Book.where("title LIKE?","#{word}%")
		elsif search == "backward_match"
			@book = Book.where("title LIKE?","%#{word}")
		elsif search == "perfect_match"
			@book = Book.where(title: word)
		elsif search == "partial_match"
			@book = Book.where("title LIKE?","%#{word}%")
		else
			@book = Book.all
		end
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book, counter_cache: :favorite_count

	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false
  # follow
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}

  def already_favorited?(book)
  	self.favorites.exists?(book_id: book.id)
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end


        def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where(name: word)
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

 
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'Signed out successfully.'
  end

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		comment = BookComment.new(book_comment_params)
		comment.user_id = current_user.id
		comment.book_id = book.id
		comment.save
        redirect_to book_path(book)
	end

	def destroy
		BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
		redirect_to book_path(params[:book_id])
	end

	private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user =current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @books = Book.all
    @book = Book.find(params[:book_id])
    @favorite = @book.favorites.new(user_id: current_user.id)
    @favorite.save
  end

  def destroy
    @books = Book.all
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

   def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
	def search
	@range = params[:range]
	search = params[:search]
    word = params[:word]

    if @range == "1"
    	@user = User.search(search,word)
    else
    	@book = Book.search(search,word)
    end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	  def current_user?(user)
     user == current_user
  end
end

app/views/book_comments/create.js.erb
$("text_area").val("");
$("input").val("");

app/views/books/_book.html.erb
<td>
  <%= link_to(book.user) do %>
    <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
  <% end %>
</td>
<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
<td><%= book.body %></td>
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <span class="fas fa-heart" aria-hidden="true" style="color: red;"></span>
        <%= book.favorites.count%>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <span class="far fa-heart" aria-hidden="true" style="color: red;"></span>
        <%= book.favorites.count %>
    <% end %>
  <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_book_comment.html.erb
<% book.book_comments.each do |book_comment| %>
<li>
    <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
    <%= book_comment.user.name%>
    <%= book_comment.comment%>
    <% if book_comment.user == current_user %>
    <%= link_to "削除", book_book_comment_path(book_comment.book,book_comment),method: :delete, class: "btn-sm btn-danger"%>
    <% end %>
</li>
<% end %>

app/views/books/_favorite.html.erb
<% if Favorite.find_by(user_id: current_user.id, book_id: book.id) %>
  <%= link_to "/books/#{book.id}/favorites", method: :delete, remote: true do %>
    <i class="material-icons">star</i>
    <% end %>
<% else %>
  <%= link_to "/books/#{book.id}/favorites", method: :post, remote: true do %>
    <i class="material-icons">star_border</i>
    <% end %>
<% end %>
<%= book.favorites.length %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr class="book_<%= book.id %>">
        <%= render 'book', book: book %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_newform.html.erb
<% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_with model:book do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_show.html.erb
<tr>
    <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
        <%= book.user.name %>
        <% end %>
    </td>
    <td>
        <%= link_to book.title, book_path(book) %>
    </td>
    <td>
        <%= book.body %>
    </td>
     <td class="book_<%= book.id %>">
        <%= render 'book', book: book %>
      </td>
    <td>
        <p>コメント数 :
            <%= book.book_comments.count%>
        </p>
    </td>
    <%if book.user.id == current_user.id %>
    <td>
        <%= link_to "Edit", edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %>
    </td>
    <td>
        <%= link_to "Destroy", book_path(book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book.id}" %>
    </td>
    <% end %>
</tr>

app/views/books/_show_book.html.erb
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <span class="fas fa-heart" aria-hidden="true" style="color: red;"></span>
        <%= book.favorites.count%>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <span class="far fa-heart" aria-hidden="true" style="color: red;"></span>
        <%= book.favorites.count %>
    <% end %>
  <% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
    <div class="col-xs-3">
        <h2>User info</h2>
        <%= render 'users/profile', user: current_user %>
        <h2>New book</h2>
        <%= render 'books/newform', book: @book %>
    </div>
    <div class="col-xs-9">
        <h2>Books index</h2>
        <!--books一覧 -->
        <%= render 'index', books: @books%>
        </table>
        <!--books一覧 -->
    </div>
</div>

app/views/books/show.html.erb
<div class="row">
    <div class="col-xs-3">
        <h2>User info</h2>
        <%= render 'users/profile', user: @user %>
        <h2>New book</h2>
        <%= render 'books/newform', book: @book_new %>
    </div>
    <div class="col-xs-9">
        <h2>Book detail</h2>
        <table class="table">
            <tr>
                <td>
                    <%= link_to user_path(@book.user) do %>
                    <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
                    <%= @book.user.name %>
                    <% end %>
                </td>
                <td>
                    <%= link_to @book.title, book_path(@book) %>
                </td>
                <td>
                    <%= @book.body %>
                </td>
                <td>
                    <div class="book2_<%= @book.id %>" >
                    <%= render 'show_book', book: @book %>
                </div>
                </td>
                <td>
                    <p>コメント数 :
                        <%= @book.book_comments.count%>
                    </p>
                </td>
                <%if @book.user.id == current_user.id %>
                <td>
                    <%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %>
                </td>
                <td>
                    <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
                </td>
                <% end %>
            </tr>
        </table>
        <%= render "book_comment", book: @book %>
        <%= form_with model:[@book, @book_comment] do |f| %>
        <%= f.text_area :comment, rows:'5'%>
        <%= f.submit "送信", class: "btn-sm" %>
        <% end %>
    </div>
</div>

app/views/favorites/create.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'books/book',  book: @book ) %>")
$(".book2_<%= @book.id %>").html("<%= j(render 'books/show_book',  book: @book ) %>")

app/views/favorites/destroy.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'books/book',  book: @book ) %>")
$(".book2_<%= @book.id %>").html("<%= j(render 'books/show_book',  book: @book ) %>")

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/relationships/index.html.erb
 <% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/searchs/search.html.erb
<h2>Results index</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
　<% if @range == '2' %>
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @book.each do |book| %>
     <tr>
      <td>
       <%= link_to(book.user) do %>
       <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
       <% end %>
      </td>
      <td>
       <%= link_to book.title, book, class: "book_#{book.id}" %> 
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>

  <% else %>
  <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name%></td>
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
     </tr>
    <% end %>
   </tbody>
   <% end %>
 </table>

app/views/users/_follow.html.erb
 <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>
  <% else %>
     <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>
  <% end %>
  </div>
<% end %>  

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<% user ||= current_user %>
	<tr>
		<th>follow</th>
		<th>
			<a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.followings.count %>
    </strong>
		</th>
	</tr>
	<tr>
		<th>follower</th>
		<th>
			 <a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
		</th>
	</tr>
		<th>
			<% unless current_user?(user) %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>
  <% else %>
     <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>
  <% end %>
  </div>
<% end %> 
		</th>
</table>

<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/_stats.html.erb
 <% user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
    <div class="col-xs-3">
        <h2>User info</h2>
        <%= render 'users/profile', user: current_user %>
        <h2>New book</h2>
        <%= render 'books/newform', book: @book %>
    </div>
    <div class="col-xs-9">
        <h2>Users</h2>
        <!--users一覧 -->
        <table class="table">
            <thead>
                <tr>
                    <th>image</th>
                    <th>name</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
                    </td>
                    <td>
                        <%= user.name %>
                    </td>
                    <td><a href="<%= following_user_path(user) %>">
                            <strong id="following" class="stat">
                                <%= user.followings.count %>
                            </strong>
                            following
                        </a></td>
                    <td><a href="<%= followers_user_path(user) %>">
                            <strong id="followers" class="stat">
                                <%= user.followers.count %>
                            </strong>
                            followers
                        </a></td>
                    <% unless current_user?(user) %>
                    <td>
                        <% if current_user.following?(user) %>
                        <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
                        <%= f.submit "Unfollow" %>
                        <% end %>
                        <% else %>
                        <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
                        <%= f.hidden_field :following_id %>
                        <%= f.submit "Follow" %>
                        <% end %>
                        <% end %>
                    </td>
                    <% else %>
                    <td>
                        <span></span>
                    </td>
                    <% end %>
                    <td>
                        <%= link_to "Show", user_path(user), class: "user_#{user.id}" %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
		
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><p>コメント数 : <%= @book.book_comments.count%></p></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="follow">
<% @user.followings.each do |user| %>
<table class="follow-box">
<tr>
	<td>
		<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
	</td>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>
</div>

app/views/users/show_follower.html.erb
<div class="follower">
<% @user.followers.each do |user| %>
<table class= "follower-box">
<tr>
  <td>
  	<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
  </td>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>
</div>